version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore WebAppCodepipline.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output WebAppCodepipline.csproj
      - grep -Fq "Oliver" index.html
      - grep -Fq "Levi" index.html
  post_build:
    commands:
      - echo "Deployed to s3"
artifacts:
  files:
    - '**/*'
    - ./build_output
   